### ISSUE TITLE
Wake Word on XCode 12.2 Simulator Not Working

### ISSUE THREAD

**Issue by schwamic** [snipsco-samples/quickstart-swift#1]
After following the tutorial, I am not able to wake up my app. Maybe Snips doesn't work on the simulator?

**Comment by erksch** [comment]
Having a similar issue. My console displays: 
`Snips error: SnipsPlatformError(message: "couldn\'t find any hotword model\n")`

Is no default "Hey Snips" model provided perhabs?

**Comment by klefevre** [comment]
Yes, it does but making it work isn't straightforward. Personally, I've made it work with a Bluetooth headset and by activating Siri first on the simulator.
